// Package approvals records that a human has approved write access for a
// single `rein run` invocation. One approval covers all writes within
// that run; the RUN LIFETIME is the bound (not a clock TTL).
//
// # Per-run keying (concurrency)
//
// Approvals are keyed by a per-run nonce (REIN_RUN_ID, generated by
// `rein run` from crypto/rand). Each run owns exactly two files under the
// state dir, named by its run id:
//
//   - runs/<run-id>.json      — a session snapshot (RunContext) the
//     credential HELPER writes just-in-time so an out-of-process grant
//     (tmux popup / another terminal) can learn WHICH session it is
//     approving. The popup and the "approve from another terminal"
//     recovery run outside the helper's process tree, so they see neither
//     REIN_RUN_ID nor REIN_SESSION_FILE — the on-disk snapshot is the
//     only bridge.
//   - approvals/<run-id>.json — the approval Record for this run.
//
// Because each run writes only its own files, two concurrent `rein run`s
// on different sessions never race a shared file: approving run A cannot
// satisfy run B, and A's exit cannot clear B's approval.
//
// The run id is implicit in the filename, so Record has no RunID field.
//
// # Invalidation
//
// An approval invalidates whenever ANY of the session's identity-shaping
// fields change: ID, Role, Repos, or Issue. SignatureOf hashes those
// fields; on each ConfirmWrite the caller compares the stored signature
// to the LIVE session's signature. A mismatch is treated as "no approval"
// and forces a re-prompt — this catches a mid-run dev-session.yaml scope
// edit (e.g. an added repo) so a carried approval can't silently cover
// expanded scope.
//
// # No security TTL
//
// Run-id uniqueness means a stale approval file from a crashed run is
// never reusable: no future run shares the random id. So Valid has NO
// time gate — a long agent session keeps its approval for the whole run.
// Record.ExpiresAt is retained ONLY as a sweep heuristic for orphaned
// files (Sweep) and for `rein approval status` display; it is never a
// re-prompt trigger within a run.
//
// # Lifecycle
//
// `rein run` owns lifecycle: it generates the run id, exports it, clears
// this run's two files on exit (deferred), and sweeps orphaned run/
// approval files on launch (Sweep). SIGKILL bypasses the deferred clear;
// the launch Sweep is the backstop for those orphans.
//
// # Escape hatches
//
// Force a re-prompt without waiting for run exit:
//   - `rein approval clear --run-id <X>` (one run) or `rein approval
//     clear` (all runs)
//   - Edit dev-session.yaml (changes the signature)
package approvals

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"syscall"
	"time"

	"github.com/TomHennen/rein/internal/session"
)

// Record is the on-disk shape of an approval.
type Record struct {
	// Signature is the hash of the session fields the approval covers.
	// Mismatch with the current session's signature invalidates the
	// approval — the operator changed scope and must re-approve.
	Signature string `json:"signature"`

	// SessionID is recorded for log/audit clarity; the actual identity
	// check is via Signature (which includes ID).
	SessionID string `json:"session_id"`

	// ApprovedAt is when the human typed the issue number.
	ApprovedAt time.Time `json:"approved_at"`

	// ExpiresAt is retained ONLY as a sweep heuristic + status display.
	// It is NOT a re-prompt trigger: see package doc, "No security TTL".
	ExpiresAt time.Time `json:"expires_at"`
}

// RunContext is the just-in-time session snapshot the credential HELPER
// writes (WriteRunContext) so an out-of-process `rein approval grant
// --run-id X` (tmux popup / another terminal) can learn which session it
// is approving. The helper is the only process holding BOTH REIN_RUN_ID
// and the resolved session, so it is the writer.
type RunContext struct {
	// Session is the resolved session for this run.
	Session session.Session `json:"session"`

	// RunPID is the pid of the owning `rein run` process (REIN_RUN_PID),
	// used by Sweep's liveness probe. 0 means unknown.
	RunPID int `json:"run_pid"`

	// WrittenAt is when the helper wrote this snapshot.
	WrittenAt time.Time `json:"written_at"`
}

// RunStatus is one entry returned by List, for `rein approval status`.
type RunStatus struct {
	RunID       string
	Context     RunContext // zero-value Session if runs/<id>.json missing
	Approval    Record     // zero-value if approvals/<id>.json missing
	HasContext  bool
	HasApproval bool
	Live        bool // RunPID liveness probe result
}

// SignatureOf computes the deterministic signature for a session. Any
// change to ID, Role, Repos, or Issue produces a different signature.
// Repo ordering is normalized via sort so a re-ordered list doesn't
// invalidate an existing approval.
//
// Created is intentionally NOT in the signature: the approval is keyed
// to the SESSION (operator's intent), not to its file mtime.
func SignatureOf(s session.Session) string {
	repos := append([]string{}, s.Repos...)
	sort.Strings(repos)
	h := sha256.New()
	fmt.Fprintf(h, "id=%s\n", s.ID)
	fmt.Fprintf(h, "role=%s\n", s.Role)
	fmt.Fprintf(h, "repos=%s\n", strings.Join(repos, ","))
	fmt.Fprintf(h, "issue=%d\n", s.Issue)
	return hex.EncodeToString(h.Sum(nil))
}

// Valid reports whether rec covers the expected signature. There is NO
// time gate: run-id uniqueness means a stale file is never reusable by a
// future run, so the RUN LIFETIME is the bound (not a TTL). ExpiresAt is
// retained on the record only for Sweep + `status` display.
func Valid(rec Record, expected string) bool {
	return rec.Signature != "" && expected != "" && rec.Signature == expected
}

// RunApprovalPath returns approvals/<run-id>.json under stateDir.
func RunApprovalPath(stateDir, runID string) string {
	return filepath.Join(stateDir, "approvals", safeRunID(runID)+".json")
}

// RunContextPath returns runs/<run-id>.json under stateDir (the session
// snapshot the helper writes).
func RunContextPath(stateDir, runID string) string {
	return filepath.Join(stateDir, "runs", safeRunID(runID)+".json")
}

// safeRunID defends against a malformed/path-traversing --run-id. The
// generator emits base64url (no slashes), so this is belt-and-suspenders:
// filepath.Base strips any directory components a hand-passed id might
// carry.
func safeRunID(runID string) string {
	return filepath.Base(runID)
}

// Read returns the approval record at path. Missing-file is reported
// as a distinguishable error (os.ErrNotExist via errors.Is).
func Read(path string) (Record, error) {
	body, err := os.ReadFile(path)
	if err != nil {
		return Record{}, err
	}
	var rec Record
	if err := json.Unmarshal(body, &rec); err != nil {
		return Record{}, fmt.Errorf("parse %s: %w", path, err)
	}
	return rec, nil
}

// ReadApproval reads approvals/<run-id>.json.
func ReadApproval(stateDir, runID string) (Record, error) {
	return Read(RunApprovalPath(stateDir, runID))
}

// WriteApproval atomically writes the approval record for runID.
func WriteApproval(stateDir, runID string, rec Record) error {
	body, err := json.Marshal(rec)
	if err != nil {
		return fmt.Errorf("marshal approval: %w", err)
	}
	return writeAtomic(RunApprovalPath(stateDir, runID), body)
}

// ReadRunContext reads runs/<run-id>.json. Missing-file is reported as
// os.ErrNotExist (errors.Is-distinguishable).
func ReadRunContext(stateDir, runID string) (RunContext, error) {
	body, err := os.ReadFile(RunContextPath(stateDir, runID))
	if err != nil {
		return RunContext{}, err
	}
	var rc RunContext
	if err := json.Unmarshal(body, &rc); err != nil {
		return RunContext{}, fmt.Errorf("parse run context %s: %w", RunContextPath(stateDir, runID), err)
	}
	return rc, nil
}

// WriteRunContext atomically writes the session snapshot for runID.
// Idempotent: overwriting an existing snapshot is fine.
func WriteRunContext(stateDir, runID string, rc RunContext) error {
	body, err := json.Marshal(rc)
	if err != nil {
		return fmt.Errorf("marshal run context: %w", err)
	}
	return writeAtomic(RunContextPath(stateDir, runID), body)
}

// ClearRun removes BOTH runs/<id>.json and approvals/<id>.json. Missing
// files are not an error; idempotent (safe to call twice).
func ClearRun(stateDir, runID string) error {
	var firstErr error
	for _, p := range []string{RunContextPath(stateDir, runID), RunApprovalPath(stateDir, runID)} {
		if err := os.Remove(p); err != nil && !errors.Is(err, os.ErrNotExist) && firstErr == nil {
			firstErr = err
		}
	}
	return firstErr
}

// List returns one RunStatus per known run id, scanning both runs/ and
// approvals/. A run with only one of the two files still appears (with
// the corresponding Has* false), so `status` surfaces partial state.
func List(stateDir string) ([]RunStatus, error) {
	ids := map[string]bool{}
	for _, sub := range []string{"runs", "approvals"} {
		entries, err := os.ReadDir(filepath.Join(stateDir, sub))
		if err != nil {
			if errors.Is(err, os.ErrNotExist) {
				continue
			}
			return nil, err
		}
		for _, e := range entries {
			if e.IsDir() {
				continue
			}
			name := e.Name()
			if !strings.HasSuffix(name, ".json") {
				continue
			}
			ids[strings.TrimSuffix(name, ".json")] = true
		}
	}
	out := make([]RunStatus, 0, len(ids))
	for id := range ids {
		st := RunStatus{RunID: id}
		if rc, err := ReadRunContext(stateDir, id); err == nil {
			st.Context = rc
			st.HasContext = true
			st.Live = pidAlive(rc.RunPID)
		}
		if rec, err := ReadApproval(stateDir, id); err == nil {
			st.Approval = rec
			st.HasApproval = true
		}
		out = append(out, st)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].RunID < out[j].RunID })
	return out, nil
}

// Sweep removes orphaned run/approval files whose owning `rein run` is
// gone. Liveness is a signal-0 probe on RunContext.RunPID: a live pid is
// NEVER swept regardless of age (so a long-running >maxAge session keeps
// its approval — a mid-run re-prompt is forbidden). maxAge is only a
// backstop for records whose RunPID is 0/unknown or whose context file is
// missing/corrupt. Best-effort: returns the first error for logging only;
// callers must not block launch on it.
func Sweep(stateDir string, maxAge time.Duration, now time.Time) error {
	statuses, err := List(stateDir)
	if err != nil {
		return err
	}
	var firstErr error
	for _, st := range statuses {
		if shouldSweep(st, maxAge, now) {
			if err := ClearRun(stateDir, st.RunID); err != nil && firstErr == nil {
				firstErr = err
			}
		}
	}
	return firstErr
}

// shouldSweep decides whether a run's files are orphaned.
func shouldSweep(st RunStatus, maxAge time.Duration, now time.Time) bool {
	// A live owning process is authoritative: keep, regardless of age.
	if st.HasContext && st.Live {
		return false
	}
	// Known-dead owning pid: orphan, sweep.
	if st.HasContext && st.Context.RunPID != 0 && !st.Live {
		return true
	}
	// Unknown pid (0) or no/corrupt context: fall back to the age backstop.
	ts := st.Context.WrittenAt
	if !st.HasContext {
		ts = st.Approval.ApprovedAt
	}
	if ts.IsZero() {
		// No timestamp to judge by and no live process: treat as orphan.
		return true
	}
	return now.Sub(ts) > maxAge
}

// pidAlive reports whether pid names a live process via a signal-0 probe.
// pid <= 0 is never alive. A reused pid is acceptable here (run-id
// uniqueness means a future run never reads a stale file), so we do not
// guard against pid reuse — proportionate for Shape B (issue #7).
func pidAlive(pid int) bool {
	if pid <= 0 {
		return false
	}
	proc, err := os.FindProcess(pid)
	if err != nil {
		return false
	}
	err = proc.Signal(syscall.Signal(0))
	if err == nil {
		return true
	}
	// EPERM means the process exists but is owned by another uid — still
	// "alive" for our purposes. ESRCH means no such process.
	return errors.Is(err, syscall.EPERM)
}

// writeAtomic writes body to path atomically: a temp file in the same
// directory, chmod 0600, then rename. The parent dir is created 0700.
func writeAtomic(path string, body []byte) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("mkdir %s: %w", dir, err)
	}
	tmp, err := os.CreateTemp(dir, filepath.Base(path)+".*")
	if err != nil {
		return fmt.Errorf("create temp: %w", err)
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName) // no-op once rename succeeds
	if err := tmp.Chmod(0o600); err != nil {
		tmp.Close()
		return err
	}
	if _, err := tmp.Write(body); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmpName, path)
}
