// Package approvals records that a human has approved write access for a
// single `rein run` invocation. One approval covers all writes within
// that run; the RUN LIFETIME is the bound (not a clock TTL).
//
// # Per-run keying (concurrency)
//
// Approvals are keyed by a per-run nonce (REIN_RUN_ID, generated by
// `rein run` from crypto/rand). Each run owns exactly two files under the
// state dir, named by its run id:
//
//   - runs/<run-id>.json      — a session snapshot (RunContext) the
//     credential HELPER writes just-in-time so an out-of-process grant
//     (tmux popup / another terminal) can learn WHICH session it is
//     approving. The popup and the "approve from another terminal"
//     recovery run outside the helper's process tree, so they see neither
//     REIN_RUN_ID nor REIN_SESSION_FILE — the on-disk snapshot is the
//     only bridge.
//   - approvals/<run-id>.json — the approval Record for this run.
//
// Because each run writes only its own files, two concurrent `rein run`s
// on different sessions never race a shared file: approving run A cannot
// satisfy run B, and A's exit cannot clear B's approval.
//
// The run id is implicit in the filename, so Record has no RunID field.
//
// # Invalidation
//
// An approval invalidates whenever ANY of the session's identity-shaping
// fields change: ID, Role, or Repos. SignatureOf hashes those fields; on
// each write-gate check the caller compares the stored signature to the
// LIVE session's signature. A mismatch is treated as "no approval" — and
// invalidates the whole record INCLUDING its confirmed-issue set — this
// catches a mid-run dev-session.yaml scope edit (e.g. an added repo) so a
// carried approval can't silently cover expanded scope.
//
// The bound ISSUE is deliberately NOT part of the signature (issue #35,
// decision A in data form): the issue moved from the *identity* of the
// approval to its *content* — the run's confirmed-issue SET
// (Record.Issues), appended to by `rein declare <n>` + the human's Form A
// confirmation. Validity = signature match AND (for pushes) the declared
// issue ∈ Issues; for non-push writes, a non-empty set.
//
// # No security TTL
//
// Run-id uniqueness means a stale approval file from a crashed run is
// never reusable: no future run shares the random id. So Valid has NO
// time gate — a long agent session keeps its approval for the whole run.
// Record.ExpiresAt is retained ONLY as a sweep heuristic for orphaned
// files (Sweep) and for `rein approval status` display; it is never a
// re-prompt trigger within a run.
//
// # Lifecycle
//
// `rein run` owns lifecycle: it generates the run id, exports it, clears
// this run's two files on exit (deferred), and sweeps orphaned run/
// approval files on launch (Sweep). SIGKILL bypasses the deferred clear;
// the launch Sweep is the backstop for those orphans.
//
// # Escape hatches
//
// Force a re-prompt without waiting for run exit:
//   - `rein approval clear --run-id <X>` (one run) or `rein approval
//     clear` (all runs)
//   - Edit dev-session.yaml (changes the signature)
//
// # Write-token ledger (issue #20)
//
// A run owns a THIRD per-run artifact: writes/<run-id>.jsonl — an
// append-only ledger of the write tokens minted during the run (one
// tokencache.Entry per line). The credential HELPER appends a line on
// each successful write mint (AppendWriteToken); `rein run` reads the
// ledger on child exit (ReadWriteTokens), best-effort revokes each
// still-valid token, then clears the file (ClearRun removes it along
// with the other two). This tightens a successful push's effective
// write-token lifetime from GitHub's native ~1h down to the run
// duration. SIGKILL of `rein run` skips the exit-revoke; those tokens
// then live to their native TTL (the accepted floor) and the orphaned
// ledger is reaped by the launch Sweep.
//
// SECURITY: this is the one place rein persists a WRITE-tier token
// value to disk. It is unavoidable for cross-process revoke — GitHub's
// revoke API (DELETE /installation/token) is authenticated BY the token
// itself; there is no revoke-by-id, so the revoking process must hold
// the token value. The exposure is bounded: mode 0600 in a 0700 parent,
// deleted as soon as the run exits, and the token is already reachable
// to any same-uid process during the run (issue #7 — the Shape B
// limitation the Phase 1 sandbox closes). The read-token cache
// (internal/tokencache) already persists a read token the same way.
package approvals

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"syscall"
	"time"

	"github.com/TomHennen/rein/internal/brokercore"
	"github.com/TomHennen/rein/internal/session"
	"github.com/TomHennen/rein/internal/tokencache"
)

// ConfirmedIssue is one human-confirmed issue in a run's confirmed set
// (issue #35). The Title/State are a SNAPSHOT taken at confirm time (the
// design.md:758 issue snapshot — they inform the human and the audit
// trail but never authorize anything). CanonicalURL is the issue's
// canonical REST URL — the TM-G6 transfer anchor (design.md:753): a 301
// on it later means the issue was transferred and the confirmation must
// be invalidated.
type ConfirmedIssue struct {
	Number       int       `json:"number"`
	Repo         string    `json:"repo"`
	Title        string    `json:"title"` // snapshot at confirm time
	State        string    `json:"state"`
	IsPR         bool      `json:"is_pr,omitempty"` // GitHub shares the number space
	CanonicalURL string    `json:"canonical_url"`   // TM-G6 anchor
	ConfirmedAt  time.Time `json:"confirmed_at"`
}

// Record is the on-disk shape of an approval.
type Record struct {
	// Signature is the hash of the session fields the approval covers
	// (ID, Role, Repos — NOT the issue; see the package doc). Mismatch
	// with the current session's signature invalidates the approval —
	// the operator changed scope and must re-approve.
	Signature string `json:"signature"`

	// SessionID is recorded for log/audit clarity; the actual identity
	// check is via Signature (which includes ID).
	SessionID string `json:"session_id"`

	// Issues is the run's confirmed-issue set (issue #35): each
	// `rein declare <n>` the human approves appends here. Writes flow
	// when the signature matches AND (push refs resolve to a confirmed
	// issue | non-push write and the set is non-empty).
	Issues []ConfirmedIssue `json:"issues,omitempty"`

	// ApprovedAt is when the human confirmed the first issue.
	ApprovedAt time.Time `json:"approved_at"`

	// ExpiresAt is retained ONLY as a sweep heuristic + status display.
	// It is NOT a re-prompt trigger: see package doc, "No security TTL".
	ExpiresAt time.Time `json:"expires_at"`
}

// HasIssue reports whether the record's confirmed set contains issue
// `number` homed in `repo`.
//
// The repo comparison NORMALIZES both sides with the same semantics
// session.Contains uses (brokercore.RepoFromPath: strip a leading slash, a
// trailing slash, and a ".git" suffix; then case-fold — GitHub is
// case-preserving but case-insensitive on path). Normalizing HERE, in the
// comparator, is deliberate: this is the security-relevant check (the
// push-ref cross-check calls it with a repo derived from the git
// smart-HTTP URL, where `/o/r.git/git-receive-pack` yields "o/r.git",
// while a declare records the bare "o/r" it resolved from the session).
// A raw compare would deny a correctly declared, confirmed, correctly
// named push — telling the human to redo a declare that IS recorded — for
// every remote using GitHub's default `.git` clone URL. Correctness of the
// gate must not depend on caller hygiene.
//
// An unparseable repo on either side normalizes to "" and never matches
// (fail closed).
func (r Record) HasIssue(repo string, number int) bool {
	want := normalizeRepo(repo)
	if want == "" {
		return false
	}
	for _, ci := range r.Issues {
		if ci.Number == number && normalizeRepo(ci.Repo) == want {
			return true
		}
	}
	return false
}

// normalizeRepo canonicalizes an "owner/name" for comparison, delegating
// the parse to the single canonical helper (brokercore.RepoFromPath — the
// same one session.Contains and the proxy use) and lowercasing. Returns ""
// if the input isn't owner/name-shaped.
func normalizeRepo(s string) string {
	return strings.ToLower(brokercore.RepoFromPath(s))
}

// RunContext is the just-in-time session snapshot the credential HELPER
// writes (WriteRunContext) so an out-of-process `rein approval grant
// --run-id X` (tmux popup / another terminal) can learn which session it
// is approving. The helper is the only process holding BOTH REIN_RUN_ID
// and the resolved session, so it is the writer.
type RunContext struct {
	// Session is the resolved session for this run.
	Session session.Session `json:"session"`

	// Direct records whether the owning run is DIRECT mode (vs sandboxed).
	// It exists for ONE purpose (issue #69): the out-of-process grant
	// surface (`rein approval grant`, the tmux popup) must re-sign the
	// approval record after an in-prompt persist ONLY for a direct run —
	// whose credential helper reloads the widened session file and would
	// otherwise re-lock the run. A sandboxed run must NOT be re-signed (its
	// broker keeps the launch session and keys the write gate on it), so
	// the grant subcommand reads this flag to decide. Never a write gate.
	Direct bool `json:"direct,omitempty"`

	// SessionFile is the PATH the session was loaded from, or "" when it
	// came from the env fallback (no file). Transport, like PendingIssue:
	// the out-of-process grant surfaces have no REIN_SESSION_FILE and must
	// not resolve the default session, so this snapshot is the only way the
	// popup can know which file an in-prompt "save this repo" answer should
	// append to (issue #69). Never consulted by a write gate.
	SessionFile string `json:"session_file,omitempty"`

	// RunPID is the pid of the owning `rein run` process (REIN_RUN_PID),
	// used by Sweep's liveness probe. 0 means unknown.
	RunPID int `json:"run_pid"`

	// PendingIssue is the fetched-but-not-yet-confirmed issue a declare
	// wrote before prompting (issue #35). It is TRANSPORT for the
	// out-of-process grant surfaces (tmux popup / `rein approval grant
	// --run-id X`): the popup renders the Form A prompt from this
	// snapshot — it never fetches. Cleared/overwritten by the next
	// declare; never consulted by any write gate.
	PendingIssue *ConfirmedIssue `json:"pending_issue,omitempty"`

	// PendingNotice is the install-NOTICE snapshot (issue #69): transport
	// for the out-of-process notice surface (`rein approval notice
	// --run-id X`, run by the tmux popup), exactly as PendingIssue is for
	// the grant surface. It carries NO approval authority — it exists so
	// the popup can render a deep-link the human follows — and no write
	// gate ever consults it.
	PendingNotice *PendingNotice `json:"pending_notice,omitempty"`

	// WrittenAt is when the helper wrote this snapshot.
	WrittenAt time.Time `json:"written_at"`
}

// PendingNotice is a non-authorizing message awaiting the human's
// acknowledgement (issue #69): the App is not installed on a repo the agent
// asked for, so there is nothing to approve — only something to install.
type PendingNotice struct {
	Repo       string    `json:"repo"`
	Issue      int       `json:"issue,omitempty"`
	InstallURL string    `json:"install_url,omitempty"`
	AppName    string    `json:"app_name,omitempty"`
	WrittenAt  time.Time `json:"written_at"`
}

// RunStatus is one entry returned by List, for `rein approval status`.
type RunStatus struct {
	RunID       string
	Context     RunContext // zero-value Session if runs/<id>.json missing
	Approval    Record     // zero-value if approvals/<id>.json missing
	HasContext  bool
	HasApproval bool
	Live        bool      // RunPID liveness probe result
	LedgerMod   time.Time // mtime of writes/<id>.jsonl, zero if absent
}

// SignatureOf computes the deterministic signature for a session. Any
// change to ID, Role, or Repos produces a different signature. Repo
// ordering is normalized via sort so a re-ordered list doesn't
// invalidate an existing approval.
//
// The issue is deliberately NOT hashed (issue #35): it is CONTENT of the
// approval (Record.Issues), not identity — the run's issues are declared
// at runtime, not configured up front (decision A). A session file's
// legacy `issue:` field is ignored everywhere.
//
// Created is intentionally NOT in the signature: the approval is keyed
// to the SESSION (operator's intent), not to its file mtime.
func SignatureOf(s session.Session) string {
	repos := append([]string{}, s.Repos...)
	sort.Strings(repos)
	h := sha256.New()
	fmt.Fprintf(h, "id=%s\n", s.ID)
	fmt.Fprintf(h, "role=%s\n", s.Role)
	fmt.Fprintf(h, "repos=%s\n", strings.Join(repos, ","))
	return hex.EncodeToString(h.Sum(nil))
}

// Valid reports whether rec covers the expected signature. There is NO
// time gate: run-id uniqueness means a stale file is never reusable by a
// future run, so the RUN LIFETIME is the bound (not a TTL). ExpiresAt is
// retained on the record only for Sweep + `status` display.
func Valid(rec Record, expected string) bool {
	return rec.Signature != "" && expected != "" && rec.Signature == expected
}

// RunApprovalPath returns approvals/<run-id>.json under stateDir.
func RunApprovalPath(stateDir, runID string) string {
	return filepath.Join(stateDir, "approvals", safeRunID(runID)+".json")
}

// RunContextPath returns runs/<run-id>.json under stateDir (the session
// snapshot the helper writes).
func RunContextPath(stateDir, runID string) string {
	return filepath.Join(stateDir, "runs", safeRunID(runID)+".json")
}

// WriteTokenLedgerPath returns writes/<run-id>.jsonl under stateDir (the
// append-only write-token ledger the helper writes and `rein run` drains
// on exit). See the package doc's "Write-token ledger" section.
func WriteTokenLedgerPath(stateDir, runID string) string {
	return filepath.Join(stateDir, "writes", safeRunID(runID)+".jsonl")
}

// AppendWriteToken appends one write-token entry to writes/<run-id>.jsonl,
// creating the file (mode 0600) and its parent (0700) on first write.
//
// Append-only with O_APPEND so concurrent helper invocations within one
// run (e.g. parallel pushes) don't clobber each other: a single
// marshalled entry is far below PIPE_BUF, so the append is atomic on
// local filesystems. Best-effort by contract — the caller (the credential
// helper) must log+ignore any error and NEVER let it break the TM-G8
// always-return-a-credential invariant.
func AppendWriteToken(stateDir, runID string, e tokencache.Entry) error {
	path := WriteTokenLedgerPath(stateDir, runID)
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return fmt.Errorf("mkdir writes: %w", err)
	}
	line, err := json.Marshal(e)
	if err != nil {
		return fmt.Errorf("marshal write-token entry: %w", err)
	}
	line = append(line, '\n')
	f, err := os.OpenFile(path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o600)
	if err != nil {
		return fmt.Errorf("open write-token ledger: %w", err)
	}
	defer f.Close()
	if _, err := f.Write(line); err != nil {
		return fmt.Errorf("append write-token entry: %w", err)
	}
	return nil
}

// ReadWriteTokens parses writes/<run-id>.jsonl into entries. A missing
// file is reported as os.ErrNotExist (errors.Is-distinguishable) so the
// caller can treat "no writes this run" as a no-op. A torn or corrupt
// final line (possible if the run was killed mid-append) is skipped, not
// fatal — every well-formed line still yields its token to revoke.
func ReadWriteTokens(stateDir, runID string) ([]tokencache.Entry, error) {
	body, err := os.ReadFile(WriteTokenLedgerPath(stateDir, runID))
	if err != nil {
		return nil, err
	}
	var out []tokencache.Entry
	for _, line := range strings.Split(string(body), "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		var e tokencache.Entry
		if err := json.Unmarshal([]byte(line), &e); err != nil {
			continue
		}
		out = append(out, e)
	}
	return out, nil
}

// safeRunID defends against a malformed/path-traversing --run-id. The
// generator emits base64url (no slashes), so this is belt-and-suspenders:
// filepath.Base strips any directory components a hand-passed id might
// carry.
func safeRunID(runID string) string {
	return filepath.Base(runID)
}

// Read returns the approval record at path. Missing-file is reported
// as a distinguishable error (os.ErrNotExist via errors.Is).
func Read(path string) (Record, error) {
	body, err := os.ReadFile(path)
	if err != nil {
		return Record{}, err
	}
	var rec Record
	if err := json.Unmarshal(body, &rec); err != nil {
		return Record{}, fmt.Errorf("parse %s: %w", path, err)
	}
	return rec, nil
}

// ReadApproval reads approvals/<run-id>.json.
func ReadApproval(stateDir, runID string) (Record, error) {
	return Read(RunApprovalPath(stateDir, runID))
}

// WriteApproval atomically writes the approval record for runID.
func WriteApproval(stateDir, runID string, rec Record) error {
	body, err := json.Marshal(rec)
	if err != nil {
		return fmt.Errorf("marshal approval: %w", err)
	}
	return writeAtomic(RunApprovalPath(stateDir, runID), body)
}

// AppendConfirmedIssue adds a freshly human-confirmed issue to the run's
// approval record (issue #35): read-modify-write. If no record exists —
// or the existing record's signature mismatches sig (a mid-run session
// edit invalidated it, issue set included) — a FRESH record is written
// carrying only the new issue. Idempotent: re-confirming an issue already
// in the set rewrites nothing.
//
// ttl is stamped into ExpiresAt as a sweep/status heuristic only (see the
// package doc; the run lifetime is the bound).
//
// Concurrency note: two prompts cannot race in practice — declares are
// serialized through one human — and the write is atomic either way; a
// theoretical lost append re-prompts on the next declare (fail closed).
func AppendConfirmedIssue(stateDir, runID, sig, sessionID string, ci ConfirmedIssue, ttl time.Duration) error {
	now := time.Now()
	rec, err := ReadApproval(stateDir, runID)
	if err != nil || !Valid(rec, sig) {
		rec = Record{
			Signature:  sig,
			SessionID:  sessionID,
			ApprovedAt: now,
			ExpiresAt:  now.Add(ttl),
		}
	}
	if rec.HasIssue(ci.Repo, ci.Number) {
		return nil
	}
	rec.Issues = append(rec.Issues, ci)
	return WriteApproval(stateDir, runID, rec)
}

// Resign re-keys a run's approval record from oldSig to newSig, preserving
// its confirmed-issue set (issue #69).
//
// # Why this exists, and why it is not a hole
//
// A session's repo list is part of the approval SIGNATURE: change it and the
// record goes invalid, which is exactly right for a hand-edited yaml (a
// carried approval must not silently cover widened scope — see the package
// doc's Invalidation section). But the in-prompt "also save this repo?"
// answer changes the same field DELIBERATELY, in the same breath as the
// human approving that exact repo. In DIRECT mode the credential helper
// re-loads the session file on every git operation, so without this the
// human's `y` would invalidate the approval they just gave and re-lock their
// own run.
//
// This is safe precisely because of what the caller must have done first:
// the human completed the non-replayable Form A ceremony for a repo that
// passed the same-owner rule and the install-coverage probe, and rein itself
// (not an editor) performed the validated write. Nothing here re-signs a
// record for a session rein did not just author: the caller passes the
// session it wrote, and a MISMATCHED existing record (oldSig doesn't match)
// is left alone — it is already invalid and must stay so.
func Resign(stateDir, runID, oldSig, newSig, sessionID string) error {
	if runID == "" || oldSig == "" || newSig == "" || oldSig == newSig {
		return nil
	}
	rec, err := ReadApproval(stateDir, runID)
	if err != nil {
		return nil // no record yet: nothing to carry forward
	}
	if !Valid(rec, oldSig) {
		// Already invalid under the OLD session (e.g. a concurrent hand-edit).
		// Re-signing it would resurrect an approval the invalidation rule
		// deliberately killed. Leave it.
		return nil
	}
	rec.Signature = newSig
	rec.SessionID = sessionID
	return WriteApproval(stateDir, runID, rec)
}

// ConfirmedIssues returns the run's confirmed-issue set, or nil when the
// run has no approval record or its signature doesn't match sig (a
// mid-run session edit invalidates the whole record, issue set included —
// fail closed). This is the single read every write gate consults: the
// direct-mode credential helper and rein-gh shim (non-empty set ⇒ writes
// flow), and the sandboxed proxy (non-empty for API writes; per-issue
// membership for push refs).
func ConfirmedIssues(stateDir, runID, sig string) []ConfirmedIssue {
	if runID == "" {
		return nil
	}
	rec, err := ReadApproval(stateDir, runID)
	if err != nil || !Valid(rec, sig) {
		return nil
	}
	return rec.Issues
}

// ReadRunContext reads runs/<run-id>.json. Missing-file is reported as
// os.ErrNotExist (errors.Is-distinguishable).
func ReadRunContext(stateDir, runID string) (RunContext, error) {
	body, err := os.ReadFile(RunContextPath(stateDir, runID))
	if err != nil {
		return RunContext{}, err
	}
	var rc RunContext
	if err := json.Unmarshal(body, &rc); err != nil {
		return RunContext{}, fmt.Errorf("parse run context %s: %w", RunContextPath(stateDir, runID), err)
	}
	return rc, nil
}

// WriteRunContext atomically writes the session snapshot for runID.
// Idempotent: overwriting an existing snapshot is fine.
func WriteRunContext(stateDir, runID string, rc RunContext) error {
	body, err := json.Marshal(rc)
	if err != nil {
		return fmt.Errorf("marshal run context: %w", err)
	}
	return writeAtomic(RunContextPath(stateDir, runID), body)
}

// ClearRun removes a run's three per-run files: runs/<id>.json,
// approvals/<id>.json, and writes/<id>.jsonl. Missing files are not an
// error; idempotent (safe to call twice).
func ClearRun(stateDir, runID string) error {
	var firstErr error
	for _, p := range []string{RunContextPath(stateDir, runID), RunApprovalPath(stateDir, runID), WriteTokenLedgerPath(stateDir, runID)} {
		if err := os.Remove(p); err != nil && !errors.Is(err, os.ErrNotExist) && firstErr == nil {
			firstErr = err
		}
	}
	return firstErr
}

// List returns one RunStatus per known run id, scanning both runs/ and
// approvals/. A run with only one of the two files still appears (with
// the corresponding Has* false), so `status` surfaces partial state.
func List(stateDir string) ([]RunStatus, error) {
	ids := map[string]bool{}
	// "writes" is included so a run whose ONLY artifact is a write-token
	// ledger (the write-capable-role-with-no-bound-issue path: ConfirmWrite
	// is nil, so no runs/ or approvals/ file is ever written, yet a token
	// is minted and recorded) is still enumerated and thus swept when
	// orphaned. Its files use a .jsonl suffix; the others use .json.
	for _, sub := range []string{"runs", "approvals", "writes"} {
		entries, err := os.ReadDir(filepath.Join(stateDir, sub))
		if err != nil {
			if errors.Is(err, os.ErrNotExist) {
				continue
			}
			return nil, err
		}
		for _, e := range entries {
			if e.IsDir() {
				continue
			}
			id, ok := strings.CutSuffix(e.Name(), ".json")
			if !ok {
				id, ok = strings.CutSuffix(e.Name(), ".jsonl")
			}
			if !ok {
				continue
			}
			ids[id] = true
		}
	}
	out := make([]RunStatus, 0, len(ids))
	for id := range ids {
		st := RunStatus{RunID: id}
		if rc, err := ReadRunContext(stateDir, id); err == nil {
			st.Context = rc
			st.HasContext = true
			st.Live = pidAlive(rc.RunPID)
		}
		if rec, err := ReadApproval(stateDir, id); err == nil {
			st.Approval = rec
			st.HasApproval = true
		}
		if fi, err := os.Stat(WriteTokenLedgerPath(stateDir, id)); err == nil {
			st.LedgerMod = fi.ModTime()
		}
		out = append(out, st)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].RunID < out[j].RunID })
	return out, nil
}

// Sweep removes orphaned run/approval files whose owning `rein run` is
// gone. Liveness is a signal-0 probe on RunContext.RunPID: a live pid is
// NEVER swept regardless of age (so a long-running >maxAge session keeps
// its approval — a mid-run re-prompt is forbidden). maxAge is only a
// backstop for records whose RunPID is 0/unknown or whose context file is
// missing/corrupt. Best-effort: returns the first error for logging only;
// callers must not block launch on it.
func Sweep(stateDir string, maxAge time.Duration, now time.Time) error {
	statuses, err := List(stateDir)
	if err != nil {
		return err
	}
	var firstErr error
	for _, st := range statuses {
		if shouldSweep(st, maxAge, now) {
			if err := ClearRun(stateDir, st.RunID); err != nil && firstErr == nil {
				firstErr = err
			}
		}
	}
	return firstErr
}

// shouldSweep decides whether a run's files are orphaned.
func shouldSweep(st RunStatus, maxAge time.Duration, now time.Time) bool {
	// A live owning process is authoritative: keep, regardless of age.
	if st.HasContext && st.Live {
		return false
	}
	// Known-dead owning pid: orphan, sweep.
	if st.HasContext && st.Context.RunPID != 0 && !st.Live {
		return true
	}
	// Unknown pid (0) or no/corrupt context: fall back to the age backstop.
	ts := st.Context.WrittenAt
	if !st.HasContext {
		ts = st.Approval.ApprovedAt
	}
	if ts.IsZero() {
		// A "writes-only" run (write-capable role, no bound issue: ConfirmWrite
		// is nil so no run-context is ever written, yet a token is minted and
		// ledgered) has no pid to probe and no context/approval timestamp. Use
		// the ledger's mtime so the age backstop still protects a STILL-LIVE
		// such run from being reaped mid-flight by a concurrent launch's Sweep
		// — without it, ts.IsZero() would treat every writes-only run as an
		// instant orphan and clobber its not-yet-revoked tokens.
		ts = st.LedgerMod
	}
	if ts.IsZero() {
		// No timestamp to judge by and no live process: treat as orphan.
		return true
	}
	return now.Sub(ts) > maxAge
}

// pidAlive reports whether pid names a live process via a signal-0 probe.
// pid <= 0 is never alive. A reused pid is acceptable here (run-id
// uniqueness means a future run never reads a stale file), so we do not
// guard against pid reuse — proportionate for Shape B (issue #7).
func pidAlive(pid int) bool {
	if pid <= 0 {
		return false
	}
	proc, err := os.FindProcess(pid)
	if err != nil {
		return false
	}
	err = proc.Signal(syscall.Signal(0))
	if err == nil {
		return true
	}
	// EPERM means the process exists but is owned by another uid — still
	// "alive" for our purposes. ESRCH means no such process.
	return errors.Is(err, syscall.EPERM)
}

// writeAtomic writes body to path atomically: a temp file in the same
// directory, chmod 0600, then rename. The parent dir is created 0700.
func writeAtomic(path string, body []byte) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("mkdir %s: %w", dir, err)
	}
	tmp, err := os.CreateTemp(dir, filepath.Base(path)+".*")
	if err != nil {
		return fmt.Errorf("create temp: %w", err)
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName) // no-op once rename succeeds
	if err := tmp.Chmod(0o600); err != nil {
		tmp.Close()
		return err
	}
	if _, err := tmp.Write(body); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmpName, path)
}
